### ISSUE TITLE
The game runs out of memory when opening generated chests which generate TE+ enchanted books

### ISSUE THREAD

**Issue by vemboi** [Frektip/Technical-Enchant-Renewed#10]
When opening generated chests which include TE+ enchanted books the game immediatly drops its tick rate down to 0 and starts to increase RAM usage till it hits 100% and crashes.
This is using the latest version (v7.3.2b) and no external mods/data packs on a fresh world.
Crash report: [crash-2023-08-10_17.06.41-server.txt](https://github.com/Frektip/Technical-Enchant-Renewed/files/12315253/crash-2023-08-10_17.06.41-server.txt)

**Comment by Frektip** [comment]
Thank you for your report, I'm aware that the "chest loot" feature from the pack is currently unoptimized, so I will recommend disabling that feature until I release an update to solve that issue. You can do it with `/function enchantplus:config`

**Comment by Frektip** [comment]
Hi, I updated the pack with new code for the loot-table system. Could you tell me if that solve the issue?
