### ISSUE TITLE
"clic" this item

### ISSUE THREAD

**Issue by bloodyeyesblackblood** [Frektip/Technical-Enchant-Renewed#11]
the k doesn't seem to find it's way home? :p
intentional or mispelled?

**Comment by Frektip** [comment]
I think it finally find it's home in the current update I'm working on ;)

**Comment by derozero** [comment]
This is still an issue in v7.4.2 for both versions of the technical anvil

**Comment by Frektip** [comment]
Maybe it can get corrected in a hot-fix
