### ISSUE TITLE
Passive Mobs spawn as if with Geared? No meat drops

### ISSUE THREAD

**Issue by setzke** [Frektip/Technical-Enchant-Renewed#17]
Hello, playing vanilla 1.20.4 with datapack version 7.4.1. (All default settings)
Sometimes passive mobs naturally spawn with the pulsing particles, and when this happens, they have speed etc, but they also... drop nothing. Not even their meat.

Is there a way to fix this? Either no sparkling beauties (but i like chasing them!), or instead make them have a bolstered drop table?

Thank you for your time. Log doesn't show any warnings or errors pertaining to this.

![image](https://github.com/Frektip/Technical-Enchant-Renewed/assets/13110348/0b8850c8-598a-4443-b690-7cae600bc27a)
(PS If you make a new world 1.20.4 with only this datapack in the folder before initial generation, use seed "pig" and head north, you'll see cows with the effect.)

**Comment by Frektip** [comment]
Hi, when a mob has those particles it means that it has turned into an "enchanted mob". When his happen their loot-table is modified in such a way that whenever you kill them, there is a small chance they can drop a custom enchanted book. However, that also means that their vanilla loot-table is lost (overwritten).

Most of the mobs can turn into an enchanted mob, in case you want to exclude certain mobs to have a the change to turn into an enchanted mob you can modify the pack file: `data/teplus_exten/tags/entity_types/drops/ignore.json`. You need to add the correct Id from the mob you want to exclude.

**Comment by setzke** [comment]
Thanks for the info!
I'll add some mental head-canon that explains how enchanted mobs have magical properties that defy logic.
