### ISSUE TITLE
[1.19.2]Enchantment of armor doesn't work with armors(Refined Obsidian) of Mekanism Tools

### ISSUE THREAD

**Issue by Tigrex-Dai** [Frektip/Technical-Enchant-Renewed#2]
I've tried to enchant bright vision and time_breaker on the refined obsidian helmet but failed, neither on anvil nor TE+ anvil.

**Comment by Frektip** [comment]
Those are modded items that aren't supported by Technical Enchant by default. You need a "Complement" datapack designed to make those tools to work with Technical Enchant Environment.

You can create a custom Complement datapack using [Complement Creator](https://github.com/KendallP4299/Complement-Creator-for-Technical-Enchant-Renewed-)
