### ISSUE TITLE
XP-Boost 2

### ISSUE THREAD

**Issue by Johannes-Sch** [Frektip/Technical-Enchant-Renewed#3]
Hi, according to the wiki you should only be able to get XP-Boost 1 but i somehow got XP-Boost 2 on a random Sword (and added a few echantments afterwards).
Is the Wiki incorrect or is that a bug?

Thanks and kind regards

![grafik](https://user-images.githubusercontent.com/36738886/210850730-5763235f-56e7-4627-b8b1-6eab158141f0.png)

**Comment by Frektip** [comment]
Hi, the wiki has been updated, thank you for letting me know (xp Boost is ser by default to lvl 3, You can increase it more if You have access to commands)
