### ISSUE TITLE
[1.19.3] Some Items can't be (fully) disenchantet

### ISSUE THREAD

**Issue by Johannes-Sch** [Frektip/Technical-Enchant-Renewed#4]
Hi, sometimes when enchanting Items you get enchantments that are not compatible with the tool/weapon/armor.
That would not be a problem but you can't fully disentchant them, neither in the technical anvil or by dropping them on the grindstone.
However any other enchantments are getting removed jut fine.

Thank you again and kind regards
![grafik](https://user-images.githubusercontent.com/36738886/210857700-3b692319-a004-48d3-a896-1f30cbb36805.png)

**Comment by Frektip** [comment]
Yeah, I'm aware about that problem. It is a visual bug ( the enchantment isn't there actually). Sorry about that

**Comment by Frektip** [comment]
Hello again I have updated the datapack/mod and hopefully solve this issue.

Note: the mod download may be available after a couple of hours.

**Comment by Johannes-Sch** [comment]
Thanks for your fast reply, we have a lot of fun with technical enchant! :)
