### ISSUE TITLE
Lava Walker III

### ISSUE THREAD

**Issue by Johannes-Sch** [Frektip/Technical-Enchant-Renewed#5]
Hi again,
it's probably the same as last time, but according to the wiki there should only be lava walker I. However I randomly got stage III.

Thanks and kind regards
![grafik](https://user-images.githubusercontent.com/36738886/211685386-88927ae6-c31a-4731-a26b-a11441b14c40.png)

**Comment by Frektip** [comment]
Oh, you're right, I forgot to set the default value to level 1. Though, if You have v7.3.0b installed that shouldn't be a problem (I mean that you can still get Lava Walker III but the enchantment will work fine)

**Comment by Frektip** [comment]
In case You don't want that yo happen, use the config menu with `/function enchantplus:config` and You can set Lava Walker back to lvl 1
