### ISSUE TITLE
armor and enchants not working at all

### ISSUE THREAD

**Issue by Lifeless102** [Frektip/Technical-Enchant-Renewed#7]
I think this is a result of the data pack but on my single player world none of my armor or protection stops any damage, and i take the same amount if I have no armor on at all

**Comment by Lifeless102** [comment]
to revise the custom enchants work, but the traditional ones don't along with armor not providing protection.

**Comment by Frektip** [comment]
Are you sure that the datapack is the main problem? TE+ don't modify any vanilla behaviour at all, it uses vanilla's features to increase the max enchantment level

**Comment by Lifeless102** [comment]
not sure, ill check back with you if its not.

**Comment by Lifeless102** [comment]
it was different mod that was a inventory restyle, sorry for any inconvenience. The restyle mod had other files messing with vanilla armor mechanics.
